In [1]:
def get_lims_pts(list_points):
    get_lim = lambda func, axis: func([func(matrix[:, axis]) for matrix in list_points])
    x_lims = (get_lim(min, 0), get_lim(max, 0))
    y_lims = (get_lim(min, 1), get_lim(max, 1))
    return(x_lims, y_lims)

def normalize_list_in_place(list_points, get_lims_pts=get_lims_pts):
    '''
        Normalization in place. Normalization of form (x - x_min)/ (x_max - x_min)
        Inputs:
            list_points: list of arrays
                Every array represents points [x, y] by its columns.
        No outputs:
            Normalization is done in place
        
    '''
    
    def normalize_in_pl(array, x_lim, y_lim):
            min_x, max_x = x_lims
            array[:, 0] -= min_x
            array[:, 0] /= (max_x - min_x)
            
            min_y, max_y = y_lims
            array[:, 1] -= min_y
            array[:, 1] /= (max_y - min_y)
            
    x_lims, y_lims = get_lims_pts(list_points)
    for array in list_points:
        normalize_in_pl(array, x_lims, y_lims)

In [10]:
def plot_list_points(list_points, n=1):
    points = list_points[n]
    x, y = points[:,0], points[:,1]
    plt.figure(figsize=(14, 6))
    plt.scatter(x, y)
    plt.xlim(-0.1, 1.1)
    plt.ylim(-0.1, 1.1)
    plt.title(f'time := {times_list[n]:.2f}.  iterations : {iters_list[n]}')
    plt.xlabel('Unb')
    plt.ylabel('Tsp')
    plt.grid()
    plt.show()


In [18]:
from model import Sol, SolCollection, read_stations
import model as m
import numpy as np
import pandas as pd
import utilities as util
import random
from copy import deepcopy
random.seed(12334789)
%matplotlib inline
from ipywidgets import interactive, fixed
import matplotlib.pyplot as plt


In [4]:
# Read file and stations
fp = '~/Dropbox/PI/PI2/data/n30q10A.dat'
file_stations = util.read_file(fp)
stations = read_stations(file_stations) # list of stations
Sol.set_stations(stations)

In [5]:
soluciones_show = SolCollection(n_pob=25, ratio_sons=.75, ratio_mutation=.2, num_random_sols=4)
list_points, times_list, iters_list = soluciones_show.train_time(20, interactive=True, n_chks=10)
lista2 = deepcopy(list_points)
normalize_list_in_place(list_points)

---------------------------------------------------------
time := 0.01.  iterations : 1
[[ 3 11]
 [ 0 15]
 [ 4  5]
 [ 4  1]
 [ 0  5]
 [ 7  1]
 [ 6  0]
 [ 3 16]
 [ 7 12]
 [10  4]
 [ 0  1]
 [ 5  1]
 [ 0  1]
 [ 1  6]
 [ 3  2]
 [ 5  8]
 [ 5 13]
 [ 0  5]
 [ 3 20]]
[route: [21, 3, 17, 8, 26, 11, 6, 22, 13, 0, 1, 29, 4, 16, 27, 15, 23, 2, 7, 18, 12, 10, 20, 25, 24, 9, 14, 5, 28, 19]
, route: [7, 6, 25, 13, 0, 1, 24, 29, 9, 22, 16, 23, 26, 20, 2, 4, 21, 10, 12, 5, 8, 28, 19, 18, 14, 17, 27, 3, 11, 15]
, route: [6, 11, 23, 28, 9, 21, 17, 1, 3, 2, 19, 14, 13, 26, 15, 25, 5, 16, 24, 18, 12, 20, 7, 8, 10, 22, 4, 27, 0, 29]
, route: [22, 5, 28, 18, 10, 4, 11, 15, 26, 16, 9, 6, 21, 1, 27, 8, 3, 25, 29, 23, 2, 24, 14, 12, 17, 13, 7, 20, 0, 19]
, route: [5, 6, 1, 12, 15, 8, 27, 10, 14, 3, 7, 13, 25, 29, 2, 4, 9, 0, 22, 19, 11, 28, 16, 23, 18, 17, 21, 26, 20, 24]
, route: [17, 5, 20, 21, 0, 24, 12, 14, 4, 13, 16, 2, 26, 8, 22, 28, 27, 18, 10, 3, 6, 7, 15, 25, 9, 23, 1, 11, 19, 29]
, route: [1, 20, 26, 

In [17]:
interactive_plot = interactive(plot_list_points, n=(0, len(list_points)-1), list_points=fixed(list_points))
output = interactive_plot.children[-1]
output.layout.height = '600px'
interactive_plot

interactive(children=(IntSlider(value=1, description='n', max=10), Output(layout=Layout(height='600px'))), _do…

In [7]:
times = SolCollection(n_pob=25, ratio_sons=.75, ratio_mutation=.2, num_random_sols=4).train_time(
    20, ret_times=True)
times

array([[1.00000000e+01, 1.19153348e+04],
       [5.80000000e+01, 7.52931130e+03],
       [6.00000000e+01, 6.86645345e+03],
       [7.60000000e+01, 4.61189310e+03],
       [9.20000000e+01, 4.03954348e+03],
       [1.02000000e+02, 1.87012015e+03],
       [1.04000000e+02, 1.06739926e+03]])

In [8]:
times

array([[1.00000000e+01, 1.19153348e+04],
       [5.80000000e+01, 7.52931130e+03],
       [6.00000000e+01, 6.86645345e+03],
       [7.60000000e+01, 4.61189310e+03],
       [9.20000000e+01, 4.03954348e+03],
       [1.02000000e+02, 1.87012015e+03],
       [1.04000000e+02, 1.06739926e+03]])