In [1]:
from model import Sol, SolCollection, read_stations
import model as m
import numpy as np
import pandas as pd
import utilities as util
import random
from copy import deepcopy
random.seed(12334789)

In [2]:
# Read file and stations
fp = '~/Dropbox/PI/PI2/data/n5q10A.dat'
file_stations = util.read_file(fp)
stations = read_stations(file_stations) # list of stations
Sol.set_stations(stations)

In [3]:
soluciones = SolCollection(n_pob=10, ratio_sons=1, ratio_mutation=.2, num_random_sols=2)

In [4]:
soluciones

[route: [3, 4, 0, 1, 2]
, route: [0, 2, 1, 4, 3]
, route: [3, 2, 4, 0, 1]
, route: [2, 0, 1, 3, 4]
, route: [2, 0, 4, 1, 3]
, route: [2, 1, 4, 0, 3]
, route: [1, 2, 0, 3, 4]
, route: [0, 4, 1, 2, 3]
, route: [1, 4, 3, 2, 0]
, route: [2, 3, 0, 1, 4]
]

In [5]:
soluciones.medal_table()

Unb          Tsp  Sol  Pod_lev
Solution                                
1           6   466.336150    1        0
3           6   520.754515    3        1
9           6   520.754515    9        1
6           6   866.476947    6        2
0          26   856.526700    0        2
4           6  1884.870772    4        3
7          12  1855.960496    7        3
5          14  1605.878198    5        3
2          20   961.369071    2        3
8          20  1009.737474    8        3

#### Problema (puede ser más complejo que n^2)

In [6]:
soluciones.sols[1].display()

---------Solution object---------
                route: [2, 0, 1, 3, 4]
                Ends at node #: 5
                The constructive sol is: [  3   7   0   0 -10]
                Tsp cost: 520.7545147409874
                Unbalance costs: 6


In [7]:
soluciones.train_time(10)

array([[  6.        , 466.33614951],
       [ 26.        ,   0.        ]])

In [8]:
soluciones._times

{'medal_table': 7.318556308746338,
 'biased_parents': 0.31258201599121094,
 'parent_selection': 0.382108211517334,
 'reproduce': 2.0633063316345215,
 'one_gen_mutation': 0.29390907287597656}

In [9]:
soluciones2 = SolCollection(n_pob=5, ratio_sons=1, ratio_mutation=.2, num_random_sols=1)
print(soluciones2.get_paretto_sols())
soluciones2.train_time(10, interactive=False)

[[  6.         520.75451474]]


array([[  6.        , 466.33614951],
       [ 26.        ,   0.        ]])

In [10]:
soluciones2._times

{'medal_table': 8.091279745101929,
 'biased_parents': 0.22978520393371582,
 'parent_selection': 0.28267931938171387,
 'reproduce': 1.3774259090423584,
 'one_gen_mutation': 0.20528554916381836}

In [11]:
soluciones2.sols

[route: [0 3 1],
 route: [3 0 2 4],
 route: [1 4],
 route: [2 0 1 3],
 route: [1 3],
 route: [2 3 1],
 route: [0 3 2],
 route: [4 3],
 route: [4 0],
 route: [0 3 1 4]]

In [12]:
soluciones_show = SolCollection(n_pob=5, ratio_sons=1, ratio_mutation=.2, num_random_sols=1)
list_points, times_list, iters_list = soluciones_show.train_time(10, interactive=True)



---------------------------------------------------------
time := 0.00.  iterations : 1
[[0 2]
 [0 2]
 [0 3]
 [0 1]
 [0 1]]
[route: [3, 0, 4, 1, 2]
, route: [2, 1, 0]
, route: [2, 1, 3, 4, 0]
, route: [4, 2, 1, 3, 0]
, route: [1, 4, 2, 3, 0]
, route: [3 0 4 1 2]
, route: [3 0 4 1 2]
, route: [4 3 0 1 2]
, route: [3 0 4 1 2]
, route: [2 3 4 1 0]
]
---------------------------------------------------------
time := 2.50.  iterations : 893
[[0 2]
 [0 1]
 [0 1]
 [0 1]
 [0 2]]
[route: [2 3]
, route: [4 3 0 2]
, route: [1 0]
, route: [0 4 1]
, route: [4 0]
, route: [2 3]
, route: [2 3 4 1]
, route: [4 3 2 1]
, route: [2 3]
, route: [2 3 4]
]
---------------------------------------------------------
time := 5.00.  iterations : 1804
[[0 1]
 [0 2]
 [0 3]
 [0 2]
 [0 3]]
[route: [1 0 4 2]
, route: [3 2 0 4]
, route: [2 4 0]
, route: [2 0]
, route: [3 0 4]
, route: [1 0 4 2]
, route: [1 0 4]
, route: [3 0]
, route: [0 1 4]
, route: [1 0]
]
---------------------------------------------------------
ti

In [13]:
def get_lims_pts(list_points):
    get_lim = lambda func, axis: func([func(matrix[:, axis]) for matrix in list_points])
    x_lims = (get_lim(min, 0), get_lim(max, 0))
    y_lims = (get_lim(min, 1), get_lim(max, 1))
    return(x_lims, y_lims)

def normalize_list_in_place(list_points, get_lims_pts=get_lims_pts):
    '''
        Normalization in place. Normalization of form (x - x_min)/ (x_max - x_min)
        Inputs:
            list_points: list of arrays
                Every array represents points [x, y] by its columns.
        No outputs:
            Normalization is done in place
        
    '''
    
    def normalize_in_pl(array, x_lim, y_lim):
            min_x, max_x = x_lims
            array[:, 0] -= min_x
            array[:, 0] /= (max_x - min_x)
            
            min_y, max_y = y_lims
            array[:, 1] -= min_y
            array[:, 1] /= (max_y - min_y)
            
    x_lims, y_lims = get_lims_pts(list_points)
    for array in list_points:
        normalize_in_pl(array, x_lims, y_lims)

In [14]:
lista2 = deepcopy(list_points)

In [15]:
normalize_list_in_place(list_points)
get_lims_pts(list_points)

((0.0, 1.0), (0.0, 1.0))

In [16]:
get_lims_pts(lista2)

((6.0, 26.0), (0.0, 1141.615341024707))

In [17]:
%matplotlib inline
from ipywidgets import interactive
import matplotlib.pyplot as plt

def plot_list_points(n=1):
    points = list_points[n]
    x, y = points[:,0], points[:,1]
    plt.figure(figsize=(14, 6))
    plt.scatter(x, y)
    plt.xlim(-0.1, 1.1)
    plt.ylim(-0.1, 1.1)
    plt.title(f'time := {times_list[n]:.2f}.  iterations : {iters_list[n]}')
    plt.xlabel('Unb')
    plt.ylabel('Tsp')
    plt.grid()
    plt.show()
    
interactive_plot = interactive(plot_list_points, n=(0, len(list_points)-1))
output = interactive_plot.children[-1]
output.layout.height = '400px'
interactive_plot

interactive(children=(IntSlider(value=1, description='n', max=4), Output(layout=Layout(height='400px'))), _dom…